const mockItems = [
  {
    id: 1,
    name: "Handwoven Saree",
    category: "Clothing",
    description: "A beautifully crafted handwoven silk saree by local artisans.",
    price: 120,
    tags: ["traditional", "handmade", "saree"],
    image: "/images/saree.jpg",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 2,
    name: "Brass Diya Set",
    category: "Home Decor",
    description: "Authentic brass diya set to brighten up your festive celebrations.",
    price: 25,
    tags: ["diwali", "decor", "brass"],
    image: "/images/brass-diya.jpg",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 3,
    name: "Mango Pickle",
    category: "Food",
    description: "Traditional homemade mango pickle with a spicy tangy flavor.",
    price: 10,
    tags: ["pickle", "homemade", "food"],
    image: "/images/mango-pickle.jpg",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 4,
    name: "Handcrafted Wooden Toys",
    category: "Toys",
    description: "Eco-friendly and colorful wooden toys crafted by local artisans.",
    price: 15,
    tags: ["eco-friendly", "toys", "wood"],
    image: "/images/wooden-toys.jpg",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 5,
    name: "Pure Sandalwood Incense Sticks",
    category: "Spiritual",
    description: "Fragrant sandalwood incense sticks made from pure ingredients.",
    price: 5,
    tags: ["incense", "spiritual", "sandalwood"],
    image: "/images/sandalwood-incense.jpg",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 6,
    name: "Terracotta Jewelry",
    category: "Accessories",
    description: "Elegant terracotta jewelry set perfect for special occasions.",
    price: 30,
    tags: ["jewelry", "handcrafted", "terracotta"],
    image: "/images/terracotta-jewelry.jpg",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  // Similar structure repeated for more items in different categories
  {
    id: 7,
    name: "Cotton Kurta",
    category: "Clothing",
    description: "A soft cotton kurta for everyday wear, comfortable and stylish.",
    price: 35,
    tags: ["cotton", "kurta", "traditional"],
    image: "/images/cotton-kurta.jpg",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 8,
    name: "Brass Lantern",
    category: "Home Decor",
    description: "Vintage-style brass lantern to brighten up your living space.",
    price: 40,
    tags: ["lantern", "brass", "vintage"],
    image: "/images/brass-lantern.jpg",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 9,
    name: "Aloo Bhujia",
    category: "Food",
    description: "Crispy and spicy potato snack, perfect for tea time.",
    price: 8,
    tags: ["snack", "potato", "crispy"],
    image: "/images/aloo-bhujia.jpg",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 10,
    name: "Wooden Blocks",
    category: "Toys",
    description: "Set of eco-friendly wooden blocks for children to build and play.",
    price: 20,
    tags: ["eco-friendly", "blocks", "toys"],
    image: "/images/wooden-blocks.jpg",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 11,
    name: "Palo Santo Incense",
    category: "Spiritual",
    description: "Palo Santo incense sticks, known for their healing and calming properties.",
    price: 7,
    tags: ["incense", "spiritual", "calm"],
    image: "/images/palo-santo-incense.jpg",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 12,
    name: "Beaded Necklace",
    category: "Accessories",
    description: "A handcrafted beaded necklace that adds elegance to your look.",
    price: 25,
    tags: ["necklace", "beaded", "handcrafted"],
    image: "/images/beaded-necklace.jpg",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  {
    id: 13,
    name: "Silk Dupatta",
    category: "Clothing",
    description: "Luxurious silk dupatta to complement your traditional wear.",
    price: 40,
    tags: ["silk", "dupattas", "traditional"],
    image: "/images/silk-dupatta.jpg",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 14,
    name: "Wall Mirror",
    category: "Home Decor",
    description: "Decorative wall mirror with an intricate brass frame.",
    price: 60,
    tags: ["mirror", "brass", "decorative"],
    image: "/images/wall-mirror.jpg",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 15,
    name: "Lemon Pickle",
    category: "Food",
    description: "Tangy and spicy lemon pickle, perfect with Indian meals.",
    price: 12,
    tags: ["pickle", "lemon", "spicy"],
    image: "/images/lemon-pickle.jpg",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 16,
    name: "Wooden Train Set",
    category: "Toys",
    description: "Eco-friendly wooden train set for hours of fun.",
    price: 30,
    tags: ["train set", "wooden", "eco-friendly"],
    image: "/images/wooden-train-set.jpg",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 17,
    name: "Lotus Incense Holder",
    category: "Spiritual",
    description: "Lotus-shaped incense holder for a peaceful ambiance.",
    price: 15,
    tags: ["incense", "holder", "lotus"],
    image: "/images/lotus-incense-holder.jpg",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 18,
    name: "Terracotta Earrings",
    category: "Accessories",
    description: "Handcrafted terracotta earrings in beautiful designs.",
    price: 18,
    tags: ["earrings", "terracotta", "handcrafted"],
    image: "/images/terracotta-earrings.jpg",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  {
    id: 19,
    name: "Cotton Saree",
    category: "Clothing",
    description: "Lightweight and breathable cotton saree for summer wear.",
    price: 45,
    tags: ["cotton", "saree", "traditional"],
    image: "/images/cotton-saree.jpg",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 20,
    name: "Handmade Brass Candleholder",
    category: "Home Decor",
    description: "Intricately designed brass candleholder for your home.",
    price: 20,
    tags: ["brass", "candleholder", "home decor"],
    image: "/images/brass-candleholder.jpg",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 21,
    name: "Vintage Wool Shawl",
    category: "Clothing",
    description: "Warm and soft vintage wool shawl for chilly evenings.",
    price: 50,
    tags: ["vintage", "wool", "shawl"],
    image: "/images/wool-shawl.jpg",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 22,
    name: "Decorative Brass Bowl",
    category: "Home Decor",
    description: "Elegant brass bowl for serving dry fruits or as a decorative piece.",
    price: 28,
    tags: ["bowl", "brass", "decorative"],
    image: "/images/brass-bowl.jpg",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 23,
    name: "Ginger Pickle",
    category: "Food",
    description: "Spicy and tangy ginger pickle made with freshly sourced ingredients.",
    price: 9,
    tags: ["pickle", "ginger", "spicy"],
    image: "/images/ginger-pickle.jpg",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 24,
    name: "Wooden Puzzle Set",
    category: "Toys",
    description: "A fun and engaging wooden puzzle set for kids and adults alike.",
    price: 18,
    tags: ["puzzle", "wooden", "engaging"],
    image: "/images/wooden-puzzle.jpg",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 25,
    name: "Lavender Incense Sticks",
    category: "Spiritual",
    description: "Lavender incense sticks for a soothing and relaxing atmosphere.",
    price: 6,
    tags: ["incense", "lavender", "soothing"],
    image: "/images/lavender-incense.jpg",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 26,
    name: "Bohemian Necklace",
    category: "Accessories",
    description: "Handmade bohemian necklace with a mix of beads and charms.",
    price: 35,
    tags: ["bohemian", "necklace", "handmade"],
    image: "/images/bohemian-necklace.jpg",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  // Repeat for more items to create a total of 100 items
  // Add similar entries for categories like "Clothing", "Home Decor", "Food", "Toys", "Spiritual", and "Accessories"
];
// MockData/mockItems.js
const mockShops = [
  {
    shopId: 101,
    name: "Saree Heaven",
    description: "A haven for traditional and handcrafted sarees, offering a wide range of exquisite designs.",
    location: "Mumbai, India",
    contact: "+91 9876543210",
    image: "/images/saree-shop.jpg",
  },
  {
    shopId: 102,
    name: "Brass Artisans",
    description: "Specializing in authentic handcrafted brass products, perfect for your festive decorations.",
    location: "Jaipur, India",
    contact: "+91 8765432109",
    image: "/images/brass-shop.jpg",
  },
  {
    shopId: 103,
    name: "Spicy Delights",
    description: "Serving the most flavorful and spicy homemade pickles that will make your taste buds dance.",
    location: "Delhi, India",
    contact: "+91 7654321098",
    image: "/images/spicy-shop.jpg",
  },
  // Add other shops as needed
];


export { mockItems, mockShops };


