const mockItems = [
  {
    id: 1,
    name: "Handwoven Saree",
    category: "Clothing",
    description: "A beautifully crafted handwoven silk saree by local artisans.",
    price: 120,
    tags: ["traditional", "handmade", "saree"],
    image: "https://via.placeholder.com/300x200?text=Handwoven+Saree",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 2,
    name: "Brass Diya Set",
    category: "Home Decor",
    description: "Authentic brass diya set to brighten up your festive celebrations.",
    price: 25,
    tags: ["diwali", "decor", "brass"],
    image: "https://via.placeholder.com/300x200?text=Brass+Diya+Set",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 3,
    name: "Mango Pickle",
    category: "Food",
    description: "Traditional homemade mango pickle with a spicy tangy flavor.",
    price: 10,
    tags: ["pickle", "homemade", "food"],
    image: "https://via.placeholder.com/300x200?text=Mango+Pickle",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 4,
    name: "Handcrafted Wooden Toys",
    category: "Toys",
    description: "Eco-friendly and colorful wooden toys crafted by local artisans.",
    price: 15,
    tags: ["eco-friendly", "toys", "wood"],
    image: "https://via.placeholder.com/300x200?text=Wooden+Toys",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 5,
    name: "Pure Sandalwood Incense Sticks",
    category: "Spiritual",
    description: "Fragrant sandalwood incense sticks made from pure ingredients.",
    price: 5,
    tags: ["incense", "spiritual", "sandalwood"],
    image: "https://via.placeholder.com/300x200?text=Sandalwood+Incense",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 6,
    name: "Terracotta Jewelry",
    category: "Accessories",
    description: "Elegant terracotta jewelry set perfect for special occasions.",
    price: 30,
    tags: ["jewelry", "handcrafted", "terracotta"],
    image: "https://via.placeholder.com/300x200?text=Terracotta+Jewelry",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  {
    id: 7,
    name: "Cotton Kurta",
    category: "Clothing",
    description: "A soft cotton kurta for everyday wear, comfortable and stylish.",
    price: 35,
    tags: ["cotton", "kurta", "traditional"],
    image: "https://via.placeholder.com/300x200?text=Cotton+Kurta",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 8,
    name: "Brass Lantern",
    category: "Home Decor",
    description: "Vintage-style brass lantern to brighten up your living space.",
    price: 40,
    tags: ["lantern", "brass", "vintage"],
    image: "https://via.placeholder.com/300x200?text=Brass+Lantern",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 9,
    name: "Aloo Bhujia",
    category: "Food",
    description: "Crispy and spicy potato snack, perfect for tea time.",
    price: 8,
    tags: ["snack", "potato", "crispy"],
    image: "https://via.placeholder.com/300x200?text=Aloo+Bhujia",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 10,
    name: "Wooden Blocks",
    category: "Toys",
    description: "Set of eco-friendly wooden blocks for children to build and play.",
    price: 20,
    tags: ["eco-friendly", "blocks", "toys"],
    image: "https://via.placeholder.com/300x200?text=Wooden+Blocks",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 11,
    name: "Palo Santo Incense",
    category: "Spiritual",
    description: "Palo Santo incense sticks, known for their healing and calming properties.",
    price: 7,
    tags: ["incense", "spiritual", "calm"],
    image: "https://via.placeholder.com/300x200?text=Palo+Santo+Incense",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 12,
    name: "Beaded Necklace",
    category: "Accessories",
    description: "A handcrafted beaded necklace that adds elegance to your look.",
    price: 25,
    tags: ["necklace", "beaded", "handcrafted"],
    image: "https://via.placeholder.com/300x200?text=Beaded+Necklace",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  {
    id: 13,
    name: "Silk Dupatta",
    category: "Clothing",
    description: "Luxurious silk dupatta to complement your traditional wear.",
    price: 40,
    tags: ["silk", "dupattas", "traditional"],
    image: "https://via.placeholder.com/300x200?text=Silk+Dupatta",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 14,
    name: "Wall Mirror",
    category: "Home Decor",
    description: "Decorative wall mirror with an intricate brass frame.",
    price: 60,
    tags: ["mirror", "brass", "decorative"],
    image: "https://via.placeholder.com/300x200?text=Wall+Mirror",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 15,
    name: "Lemon Pickle",
    category: "Food",
    description: "Tangy and spicy lemon pickle, perfect with Indian meals.",
    price: 12,
    tags: ["pickle", "lemon", "spicy"],
    image: "https://via.placeholder.com/300x200?text=Lemon+Pickle",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 16,
    name: "Traditional Handcrafted Vase",
    category: "Home Decor",
    description: "A beautiful handcrafted vase made with eco-friendly materials.",
    price: 35,
    tags: ["vase", "handcrafted", "eco-friendly"],
    image: "https://via.placeholder.com/300x200?text=Handcrafted+Vase",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 17,
    name: "Organic Honey Jar",
    category: "Food",
    description: "Pure and organic honey, harvested from sustainable farms.",
    price: 20,
    tags: ["honey", "organic", "natural"],
    image: "https://via.placeholder.com/300x200?text=Organic+Honey",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 18,
    name: "Hand-Carved Wooden Chair",
    category: "Home Decor",
    description: "Exquisite wooden chair carved by skilled artisans.",
    price: 100,
    tags: ["wooden", "furniture", "hand-carved"],
    image: "https://via.placeholder.com/300x200?text=Wooden+Chair",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 19,
    name: "Jasmine Incense Cones",
    category: "Spiritual",
    description: "Aromatic jasmine incense cones for a calming ambiance.",
    price: 8,
    tags: ["jasmine", "incense", "aromatic"],
    image: "https://via.placeholder.com/300x200?text=Jasmine+Incense",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 20,
    name: "Terracotta Flower Pot",
    category: "Accessories",
    description: "Handcrafted terracotta flower pot for indoor plants.",
    price: 12,
    tags: ["flower pot", "terracotta", "handcrafted"],
    image: "https://via.placeholder.com/300x200?text=Terracotta+Pot",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  {
    id: 21,
    name: "Silk Scarf",
    category: "Clothing",
    description: "Luxurious silk scarf to complement any outfit.",
    price: 25,
    tags: ["scarf", "silk", "fashion"],
    image: "https://via.placeholder.com/300x200?text=Silk+Scarf",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 22,
    name: "Traditional Wall Hanging",
    category: "Home Decor",
    description: "Decorative wall hanging made from sustainable materials.",
    price: 40,
    tags: ["wall hanging", "traditional", "decor"],
    image: "https://via.placeholder.com/300x200?text=Wall+Hanging",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 23,
    name: "Mango Chutney",
    category: "Food",
    description: "Sweet and tangy mango chutney with a hint of spice.",
    price: 15,
    tags: ["chutney", "mango", "spicy"],
    image: "https://via.placeholder.com/300x200?text=Mango+Chutney",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 24,
    name: "Children's Wooden Rocking Horse",
    category: "Toys",
    description: "Eco-friendly wooden rocking horse for children.",
    price: 60,
    tags: ["rocking horse", "wooden", "toys"],
    image: "https://via.placeholder.com/300x200?text=Wooden+Rocking+Horse",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 25,
    name: "Meditation Cushion",
    category: "Spiritual",
    description: "Comfortable cushion for meditation and relaxation.",
    price: 30,
    tags: ["meditation", "cushion", "relaxation"],
    image: "https://via.placeholder.com/300x200?text=Meditation+Cushion",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 26,
    name: "Beaded Terracotta Bracelet",
    category: "Accessories",
    description: "Elegant terracotta bracelet with colorful beads.",
    price: 18,
    tags: ["bracelet", "terracotta", "beaded"],
    image: "https://via.placeholder.com/300x200?text=Terracotta+Bracelet",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
  {
    id: 27,
    name: "Designer Cotton Bedsheet",
    category: "Home Decor",
    description: "Soft cotton bedsheet with traditional Indian designs.",
    price: 50,
    tags: ["bedsheet", "cotton", "designer"],
    image: "https://via.placeholder.com/300x200?text=Cotton+Bedsheet",
    shopName: "Saree Heaven",
    shopId: 101,
  },
  {
    id: 28,
    name: "Handpainted Brass Plate",
    category: "Home Decor",
    description: "Decorative brass plate with intricate hand-painted designs.",
    price: 45,
    tags: ["plate", "brass", "decor"],
    image: "https://via.placeholder.com/300x200?text=Brass+Plate",
    shopName: "Brass Artisans",
    shopId: 102,
  },
  {
    id: 29,
    name: "Tomato Pickle",
    category: "Food",
    description: "Homemade tomato pickle with a tangy and spicy taste.",
    price: 10,
    tags: ["pickle", "tomato", "homemade"],
    image: "https://via.placeholder.com/300x200?text=Tomato+Pickle",
    shopName: "Spicy Delights",
    shopId: 103,
  },
  {
    id: 30,
    name: "Handcrafted Wooden Coasters",
    category: "Home Decor",
    description: "Set of eco-friendly wooden coasters with unique designs.",
    price: 15,
    tags: ["coasters", "wooden", "handcrafted"],
    image: "https://via.placeholder.com/300x200?text=Wooden+Coasters",
    shopName: "Wooden Wonders",
    shopId: 104,
  },
  {
    id: 31,
    name: "Aromatherapy Oil Set",
    category: "Spiritual",
    description: "Set of essential oils for aromatherapy and relaxation.",
    price: 40,
    tags: ["aromatherapy", "oil", "relaxation"],
    image: "https://via.placeholder.com/300x200?text=Aromatherapy+Oil+Set",
    shopName: "Aromatherapy Creations",
    shopId: 105,
  },
  {
    id: 32,
    name: "Terracotta Pendant",
    category: "Accessories",
    description: "Handcrafted terracotta pendant with elegant detailing.",
    price: 22,
    tags: ["pendant", "terracotta", "handcrafted"],
    image: "https://via.placeholder.com/300x200?text=Terracotta+Pendant",
    shopName: "Terracotta Treasures",
    shopId: 106,
  },
];

// MockData/mockItems.js
const mockShops = [
  {
    shopId: 101,
    name: "Saree Heaven",
    description:
      "A haven for traditional and handcrafted sarees, offering a wide range of exquisite designs.",
    location: "Mumbai, India",
    contact: "+91 9876543210",
    image: "https://via.placeholder.com/300x200?text=Saree+Shop",
  },
  {
    shopId: 102,
    name: "Brass Artisans",
    description:
      "Specializing in authentic handcrafted brass products, perfect for your festive decorations.",
    location: "Jaipur, India",
    contact: "+91 8765432109",
    image: "https://via.placeholder.com/300x200?text=Brass+Shop",
  },
  {
    shopId: 103,
    name: "Spicy Delights",
    description:
      "Serving the most flavorful and spicy homemade pickles that will make your taste buds dance.",
    location: "Delhi, India",
    contact: "+91 7654321098",
    image: "https://via.placeholder.com/300x200?text=Pickle+Shop",
  },
  {
    shopId: 104,
    name: "Wooden Wonders",
    description:
      "Offering eco-friendly wooden toys and puzzles that engage and inspire children.",
    location: "Bangalore, India",
    contact: "+91 6543210987",
    image: "https://via.placeholder.com/300x200?text=Wooden+Wonders",
  },
  {
    shopId: 105,
    name: "Aromatherapy Creations",
    description:
      "Providing high-quality incense sticks and aromatic products for relaxation and spirituality.",
    location: "Kochi, India",
    contact: "+91 5432109876",
    image: "https://via.placeholder.com/300x200?text=Aromatherapy+Creations",
  },
  {
    shopId: 106,
    name: "Terracotta Treasures",
    description:
      "Elegant terracotta jewelry and accessories handcrafted with precision.",
    location: "Hyderabad, India",
    contact: "+91 4321098765",
    image: "https://via.placeholder.com/300x200?text=Terracotta+Treasures",
  },
];



export { mockItems, mockShops };


