const mockCategories = [
  {
    id: 1,
    title: "Clothing",
    description: "Explore traditional and modern Indian apparel.",
    image: "https://via.placeholder.com/300x200?text=Clothing",
    link: "/categories/clothing",
  },
  {
    id: 2,
    title: "Home Decor",
    description: "Authentic Indian home decor items made by skilled artisans.",
    image: "https://via.placeholder.com/300x200?text=Home+Decor",
    link: "/categories/home-decor",
  },
  {
    id: 3,
    title: "Food",
    description: "Savor the taste of authentic Indian snacks and pickles.",
    image: "https://via.placeholder.com/300x200?text=Food",
    link: "/categories/food",
  },
  {
    id: 4,
    title: "Toys",
    description: "Handcrafted toys that remind you of your Indian roots.",
    image: "https://via.placeholder.com/300x200?text=Toys",
    link: "/categories/toys",
  },
  {
    id: 5,
    title: "Spiritual",
    description: "Discover spiritual items for rituals and meditation.",
    image: "https://via.placeholder.com/300x200?text=Spiritual",
    link: "/categories/spiritual",
  },
  {
    id: 6,
    title: "Accessories",
    description: "Adorn yourself with unique and handcrafted Indian accessories.",
    image: "https://via.placeholder.com/300x200?text=Accessories",
    link: "/categories/accessories",
  },
  {
    id: 7,
    title: "Handicrafts",
    description: "Fine craftsmanship in handmade artifacts.",
    image: "https://via.placeholder.com/300x200?text=Handicrafts",
    link: "/categories/handicrafts",
  },
  {
    id: 8,
    title: "Jewelry",
    description: "Intricately crafted Indian jewelry with a rich heritage.",
    image: "https://via.placeholder.com/300x200?text=Jewelry",
    link: "/categories/jewelry",
  },
  {
    id: 9,
    title: "Ayurveda",
    description: "Natural products based on ancient Ayurvedic knowledge.",
    image: "https://via.placeholder.com/300x200?text=Ayurveda",
    link: "/categories/ayurveda",
  },
  {
    id: 10,
    title: "Furniture",
    description: "Timeless, handcrafted wooden furniture for your home.",
    image: "https://via.placeholder.com/300x200?text=Furniture",
    link: "/categories/furniture",
  },
  {
    id: 11,
    title: "Carpets",
    description: "Handwoven carpets and rugs with vibrant colors.",
    image: "https://via.placeholder.com/300x200?text=Carpets",
    link: "/categories/carpets",
  },
  {
    id: 12,
    title: "Tea",
    description: "Experience the finest Indian tea varieties.",
    image: "https://via.placeholder.com/300x200?text=Tea",
    link: "/categories/tea",
  },
  {
    id: 13,
    title: "Spices",
    description: "Authentic Indian spices for your cooking.",
    image: "https://via.placeholder.com/300x200?text=Spices",
    link: "/categories/spices",
  },
  {
    id: 14,
    title: "Paintings",
    description: "Traditional and contemporary Indian artworks.",
    image: "https://via.placeholder.com/300x200?text=Paintings",
    link: "/categories/paintings",
  },
  {
    id: 15,
    title: "Stationery",
    description: "Handmade and eco-friendly Indian stationery products.",
    image: "https://via.placeholder.com/300x200?text=Stationery",
    link: "/categories/stationery",
  },
  {
    id: 16,
    title: "Bags",
    description: "Beautifully crafted bags made from natural materials.",
    image: "https://via.placeholder.com/300x200?text=Bags",
    link: "/categories/bags",
  },
  {
    id: 17,
    title: "Footwear",
    description: "Traditional Indian footwear with modern styles.",
    image: "https://via.placeholder.com/300x200?text=Footwear",
    link: "/categories/footwear",
  },
  {
    id: 18,
    title: "Utensils",
    description: "Authentic Indian cooking utensils and accessories.",
    image: "https://via.placeholder.com/300x200?text=Utensils",
    link: "/categories/utensils",
  },
  {
    id: 19,
    title: "Books",
    description: "A collection of Indian literature and spiritual books.",
    image: "https://via.placeholder.com/300x200?text=Books",
    link: "/categories/books",
  },
  {
    id: 20,
    title: "Musical Instruments",
    description: "Traditional Indian musical instruments.",
    image: "https://via.placeholder.com/300x200?text=Musical+Instruments",
    link: "/categories/musical-instruments",
  },
];

export default mockCategories;
